version: "2.1"

services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      # The user and process run as ROOT to allow backup of all files without any difficulties (eg LetsEncrypt certs)
      - PUID=0
      - PGID=0
      #NB: Default PUID and PGID is 1000
      - TZ=Australia/Perth
      # Optional Duplicati CLI arguments:
      #- CLI_ARGS=
    volumes:
      # Duplicati persistent volume for its configuration data:
      - duplicati-app-data:/config
      # Backup destination location for tar.gz (etc) files to be stored - this is a CIFS/SMB network share that maps to NAS, bind mount:
      - /media/duplicati-backups:/backups
      # Backup sources
      # Duplicati's own config data (just another mapping of the same volume listed above, for simplicity of backups):
      - duplicati-app-data:/source/duplicati-app-data
      # Nginx volumes (read-only):
      - nginxpm-data:/source/nginxpm-data:ro
      - nginxpm-letsencrypt:/source/nginxpm-letsencrypt:ro
      # NextCloud volumes (read-only):
      - nextcloud-app-data:/source/nextcloud-app-data:ro
      - nextcloud-db-data:/source/nextcloud-db-data:ro
      # Portainer volume (read-only):
      - portainer_data:/source/portainer_data:ro
    ports:
      - 8200:8200
    # Add to the pre-existing NGINX Proxy Manager network
    networks:
      - nginxpm-frontend
    restart: unless-stopped

volumes:
  # Duplicati's app data volume of course:
  duplicati-app-data:
    external: true
    name: duplicati-app-data
  # Additionally, each folder referenced in the Services config (above) for Duplicati must be sourced here:
  nginxpm-data:
    external: true
    name: nginxpm-data
  nginxpm-letsencrypt:
    external: true
    name: nginxpm-letsencrypt
  nextcloud-app-data:
    external: true
    name: nextcloud-app-data
  nextcloud-db-data:
    external: true
    name: nextcloud-db-data
  portainer_data:
    external: true
    name: portainer_data

networks:
  # Frontend network for NGINX Proxy Manager to allow proxy protection of the site
  nginxpm-frontend:
    external: true