version: "2.1"

services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      # The user and process run as ROOT to allow backup of all files without any difficulties (eg LetsEncrypt certs)
      - PUID=0
      - PGID=0
      - TZ=Australia/Perth
      # Optional Duplicati CLI arguments:
      #- CLI_ARGS=
    volumes:
      # Duplicati persistent volume for its configuration data:
      - duplicati-app-data:/config
      # Backup destination location for tar.gz (etc) files to be stored - this is a CIFS/SMB network share that maps to NAS, bind mount:
      - /media/duplicati-backups:/backups
      # Backup sources - root dir, another bind mount:
      - /var/duplicati-sources:/source
      # Backup sources
      # Nginx volumes:
      - nginxpm-data:/source/nginxpm-data
      - nginxpm-letsencrypt:/source/nginxpm-letsencrypt
      # NextCloud volumes:
      - 
    ports:
      - 8200:8200
    # Add to the pre-existing NGINX Proxy Manager network
    networks:
      - nginxpm-frontend
    restart: unless-stopped

volumes:
  # Each folder referenced in the Services config (above) for Duplicati must be sourced here:
  duplicati-app-data:
    external: true
    name: duplicati-app-data
  nginxpm-data:
    external: true
    name: nginxpm-data
  nginxpm-letsencrypt:
    external: true
    name: nginxpm-letsencrypt

networks:
  # Frontend network for NGINX Proxy Manager to allow proxy protection of the site
  nginxpm-frontend:
    external: true