version: '3'

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      # Config option customizations:
      # Scan schedule is to 10 minutes (default 1 minute), uses cron formatting. '0' disables automatic scans.
      ND_SCANNER_SCHEDULE: "*/10 * * * *"
      # Log level set to 'info'
      ND_LOGLEVEL: info  
      ND_BASEURL: ""
      # Change the cover art fetch priority to get embedded art first, then from external databases, then from cover/folder/front files
      ND_COVERARTPRIORITY: embedded, external, cover.*, folder.*, front.*
      # Enable admins to be able to change the transcoding options
      ND_ENABLETRANSCODINGCONFIG: true
      # Enable external service integrations (Spotify, LastFM)
      ND_ENABLEEXTERNALSERVICES: true
      # Configure user API keys for LastFM (via environment variables for privacy)
      ND_LASTFM_APIKEY: ${NAVIDROME_LASTFM_APIKEY}
      ND_LASTFM_SECRET: ${NAVIDROME_LASTFM_SECRET}
      # Configure user API keys for Spotify (via environment variables for privacy)
      ND_SPOTIFY_ID: ${NAVIDROME_SPOTIFY_APIKEY}
      ND_SPOTIFY_SECRET: ${NAVIDROME_SPOTIFY_SECRET}
      # Disable downloads of files
      ND_ENABLEDOWNLOADS: false
    volumes:
      # Navidrome persistent volume for its configuration data (primarily its database and cache):
      - navidrome-app-data:/data
      # Media volume - this is a SMB network share that maps to NAS, bind mount (read-only), I've set it as a variable for privacy:
      - ${NAVIDROME_MEDIA_SHARE}:/music:ro
    labels:
      # Set to update automatically via Watchtower with below label
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  # Navidrome's persistent volumes referenced above:
  navidrome-app-data:
    external: true
    name: navidrome-app-data