version: '3'

services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      # Config option customizations. Currently scan schedule is hourly, log level is set to 'info', cover art looks for embedded art first.
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_BASEURL: ""
      ND_COVERARTPRIORITY: embedded, external, cover.*, folder.*, front.*
    volumes:
      # Navidrome persistent volume for its configuration data (primarily its database and cache):
      - navidrome-app-data:/data
      # Media volume - this is a SMB network share that maps to NAS, bind mount (read-only), I've set it as a variable for privacy:
      - ${NAVIDROME_MEDIA_SHARE}:/music:ro

volumes:
  # Navidrome's persistent volumes referenced above:
  navidrome-app-data:
    external: true
    name: navidrome-app-data