version: '3'

volumes:
  # Volumes pre-exist, so set them as external
  nextcloud-app-data:
    external: true
  nextcloud-db-data:
    external: true
  nextcloud-redis-data:
    external: true

networks:
  # Add to the pre-existing NGINX Proxy Manager network
  nginxpm-frontend:
    external: true
  # Create backend network for the database to be isolated
  nextcloud-backend:
    name: nextcloud-backend

services:

  #NB: Reminder to set the all environmental variables during deployment - eg: ${VARIABLE-NAME}

  nextcloud-app:
    image: nextcloud:production-apache
    container_name: nextcloud-app
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud-app-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_APP_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - OVERWRITEPROTOCOL=https
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${NEXTCLOUD_REDIS_PASSWORD}
    #NB: Variable 'NEXTCLOUD_EXT_HOSTNAME' should be set to external FQDN hostname
    hostname: ${NEXTCLOUD_EXT_HOSTNAME}
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nginxpm-frontend
      - nextcloud-backend
    labels:
      # Set to update automatically via Watchtower with below label
      - "com.centurylinklabs.watchtower.enable=true"
    #NB: NEXTCLOUD_HOSTS1 variable should be set in format "FQDN_or_hostname:IP_address" WITH QUOTES included, example "nextcloud.domain.com:200.200.100.100"
    extra_hosts:
      - ${NEXTCLOUD_HOSTS1}

  nextcloud-db:
    image: mariadb:lts
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_APP_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud-backend
    labels:
      # Set to update automatically via Watchtower with below label
      - "com.centurylinklabs.watchtower.enable=true"

  #Redis is an object cache server used as a DB cache for improved performance
  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:latest
    command: redis-server --requirepass ${NEXTCLOUD_REDIS_PASSWORD}
    restart: always
    volumes:
      - nextcloud-redis-data:/data
    networks:
      - nginxpm-frontend
      - nextcloud-backend
    labels:
      # Set to update automatically via Watchtower with below label
      - "com.centurylinklabs.watchtower.enable=true"

  #This second container is required to run the background cron job
  nextcloud-cron:
    container_name: nextcloud-cron  
    image: nextcloud:production-apache
    restart: always
    volumes:
      - nextcloud-app-data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nginxpm-frontend
      - nextcloud-backend
    labels:
      # Set to update automatically via Watchtower with below label
      - "com.centurylinklabs.watchtower.enable=true"
