version: '3'

volumes:
  # Volumes pre-exist, so set them as external
  nextcloud-app-data:
    external: true
  nextcloud-db-data:
    external: true

networks:
  nginx-frontend:
  # Frontend nextwork also pre-exists, set as external also
    external: true
  nextcloud-backend:
    name: nextcloud-backend

services:

  #NB: Reminder to set the MYSQL password environmental variables during deployment! Test.

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud-app-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_APP_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    networks:
      - nginx-frontend
      - nextcloud-backend

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_APP_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud-backend
