
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Australia/Perth"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */5 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_NOTIF_MAIL_SSL=false"
      # Note that each of the below variables must be set in Portainer environment variables. Eg 'email_from:someaddess@mailhost.com'
      - "DIUN_NOTIF_MAIL_HOST=${email_server}"
      - "DIUN_NOTIF_MAIL_PORT=${email_port}"
      - "DIUN_NOTIF_MAIL_LOCALNAME=${email_send_hostname}"
      - "DIUN_NOTIF_MAIL_USERNAME=${email_user}"
      - "DIUN_NOTIF_MAIL_PASSWORD=${email_pass}"
      - "DIUN_NOTIF_MAIL_FROM=${email_from}"
      - "DIUN_NOTIF_MAIL_TO=${email_to}"
    labels:
      - "diun.enable=true"
    restart: always