
version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATIONS=email
      - TZ=Australia/Perth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock