
version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    # Set to restart always, important for when Watchtower updates itself!
    restart: always
    container_name: watchtower
    environment:
      # This variable sets Watchtower to ignore all containers UNLESS they have a Watchtower ENABLE Label (currently Watchtower itself, Portainer, diun, and Duplicati)
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=Loki
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=10
      # Note that each of the below variables must be set in Portainer environment variables. Eg 'email_from:someaddress@mailhost.com'
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${email_from}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${email_to}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${email_server}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${email_port}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${email_user}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${email_pass}
      # Polling interval in seconds (NB: my standard of 'monthly' equates to 2592000)
      - WATCHTOWER_POLL_INTERVAL=${poll_interval}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Added the /etc/localtime mount to avoid having to set environment variable manually. This means if the server TZ changes it should automatically flow-through to Watchtower
      - /etc/localtime:/etc/localtime:ro
    labels:
      # Set to update itself with below label
      - "com.centurylinklabs.watchtower.enable=true"